# Generated by Django 4.2.4 on 2023-09-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortalApp', '0004_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
